---
# Only if this is an ubuntu 16.04

- name: Configure apt key for docker repository
  action: apt_key url='deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial' state=present
  when: is_debian_or_ubuntu

- name: Install linux image extras
  action: apt pkg={{item}} update_cache=yes force=yes state=latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - linux-image-extra-4.4.0-38-generic
    - linux-image-extra-virtual
  when: is_debian_or_ubuntu

- name: Install Docker CE
  action: apt pkg={{item}} update_cache=yes force=yes state=latest
  with_items:
    - 'docker-ce=17.06.0~ce-0~ubuntu'
  when: is_debian_or_ubuntu

# install user to run docker commands, etc.
- user:
    name: ubuntu
    shell: /bin/bash
    groups: docker,agave,ops
    append: yes



# GC3Pie specific configuration
- name: Configure jenkins for GC3Pie
  action: template src=jenkins/templates/config.xml.j2 dest=/var/lib/jenkins/config.xml owner=jenkins
  when: inventory_hostname in groups.gc3
  notify:
    - restart jenkins

- name: create jenkins directory job
  action: file path=/var/lib/jenkins/jobs/{{item}} owner=jenkins state=directory
  with_items: j_jobs
  when: inventory_hostname in groups.gc3

- name: configure jenkins job
  action: copy src=jenkins/files/jobs/{{item}}/config.xml dest=/var/lib/jenkins/jobs/{{item}}/config.xml owner=jenkins
  with_items: j_jobs
  when: inventory_hostname in groups.gc3
  notify:
    - restart jenkins
